### ISSUE TITLE
Software/Mobile Developers

### ISSUE THREAD

**Issue by JuanSeBestia** [elcronos/COVID-19#1]
Hi, I'm Colombian dev

I'm not sure how popular or accurate would be this solution.

If it turns popular I can help you with developing Mobile/WEB/PWA solution.

I will open this issue if other devs want to join in this section.

Thanks for your work. I will read in deep in the night

**Comment by okgarces** [comment]
I am Colombian as well. 
I think we can help with the Web solution and a not complicated but useful architecture. 
Let me know when you want to chat about that.

**Comment by elcronos** [comment]
Maybe we should create different issues for the Web and Mobile development. I might create an slack channel as well to actually coordinate the work over there. In the meantime, feel free to brainstorm here. Maybe a diagram about your initial thoughts regarding the architecture and/or technologies used could be a good start. A TO-DO list with some of the initial requirements would be very useful.

**Comment by franciscohanna92** [comment]
I think we should choose a big popular and flexible framework/library for frontend. My pick would be React, and even Next.js (many things already included from scratch). 

My reason to pick React is the fact that speed is key here, and it will be better if we found lots of people to contribute, and React beign extremely popular could help.

We could go for a SPA hosted on S3 (if we get AWS credits) to reduce costs.

**Comment by elcronos** [comment]
I agree ! React is very popular ! For that reason, it would be also easier to find React devs for their maintenance. For the web frontend we can start with something very simple. Just a single page, with a drag and drop component in the middle. Additionally, we could add a button that allows to take a picture from using the webcam. I will soon upload the server using docker so you can test the service in your machine. Can anyone take the lead on this one, creating the first basic version and send a PR to the main repo? We need to start working and people will get more encourage to help once they see some more code and people working collaboratively.

**Comment by franciscohanna92** [comment]
I could start the web app project tomorrow afternoon around 15:00 UTC.

I think it will be nice to have a separate repository for it, and even start grouping all the repositories under a organization account.

**Comment by elcronos** [comment]
Everyone please have a look at this:

https://github.com/elcronos/COVID-19/blob/master/CONTRIBUTING.md

We are using Slack now for our communications

**Comment by jdnichollsc** [comment]
I can help too! React Native, NativeScript or Ionic framework to create a mobile/pwa aplicación, take me in account! :)

**Comment by JuanSeBestia** [comment]
I think we can create an Ionic app, is the way to do more fast  Web/MobileApp/PWA Application at same time

**Comment by franciscohanna92** [comment]
We are already developing a PWA using only React. Native implementations are low priority for the time being.  

Please refer to the corresponding channels on Slack and issues in Github.

I'll close this issue.
