### ISSUE TITLE
Logo & Branding

### ISSUE THREAD

**Issue by elcronos** [elcronos/COVID-19#16]
We bought the domain name fightcovid19.ai
(There were many other options we wanted to buy but were already gone !)

Help us creating an eye-catching logo for our Landing Page and Web App.

**Comment by jiminy50** [comment]
![No-COVID19](https://user-images.githubusercontent.com/62470922/77228509-dd5e6580-6bc2-11ea-8227-a8e8e865f2a7.png)
Certainly not eye-catching, however it's a placeholder until a full-time graphic designer can be sourced.
