### ISSUE TITLE
Landing Page

### ISSUE THREAD

**Issue by elcronos** [elcronos/COVID-19#17]
We bought the domain name fightcovid19.ai
(There were many other options we wanted to buy but were already gone !)

Help us creating an eye-catching landing page.

**Comment by jiminy50** [comment]
Happy to help with this. Will video call Sunday morning AWST (GMT+8).

**Comment by franciscohanna92** [comment]
@jiminy50 Please, join [the slack channel](https://join.slack.com/t/covid-19detector/shared_invite/zt-cw28jq9g-2FcPBD~zNRYLnVhr34hrRQ) (couldn't find you there).

**Comment by CalaoJuanPablo** [comment]
I can help with this, design and dev

**Comment by franciscohanna92** [comment]
It will be good to have this as a separate project from the webapp, to avoid merge conflicts and just for the sake of separate concerns. A call-to-action on the landing page should redirect the user to the app.

Maybe the landing page should go along with blogging capabilities, and thus, a tool like https://gohugo.io/ could work well. 

What do you think @CalaoJuanPablo @jiminy50 ?

**Comment by CalaoJuanPablo** [comment]
In order to keen using ReactJS we can use https://www.gatsbyjs.org/
@jiminy50 @franciscohanna92

**Comment by franciscohanna92** [comment]
@CalaoJuanPablo Yes, Gatsby sounds nice. Would you like to make a PR a kicking off the landing page project with Gatsby? Create it under `/landing-page` folder

**Comment by CalaoJuanPablo** [comment]
> @CalaoJuanPablo Yes, Gatsby sounds nice. Would you like to make a PR a kicking off the landing page project with Gatsby? Create it under `/landing-page` folder

Sure

**Comment by hectorsanchezmx** [comment]
Happy to help in here too

**Comment by diegoasencio96** [comment]
SI necesitan apoyo aca, encantado de ayudarles

**Comment by hectorsanchezmx** [comment]
@CalaoJuanPablo @franciscohanna92 I've created a PR adding support for markdown  
https://github.com/elcronos/COVID-19/pull/42

**Comment by franciscohanna92** [comment]
Landing page online already https://fightcovid19.ai/
