### ISSUE TITLE
Radiomics Features 

### ISSUE THREAD

**Issue by ankitaeclipse** [elcronos/COVID-19#2]
I am a PhD student at UNSW Sydney and work on implementing pattern recognition and computer vision techniques for rock imagery.

One of the key things I do is to use the **radiomics** implementation from medical discipline and apply it to rocks. The radiomics library allows calculating **pattern recognition based statistical descriptors** of region of interest or the image being investigated. Based on what I have read they are extremely powerful for **cancer detection** and hence, I believe its implementation for COVID-19 is crucial. 

Here's where you can read about how widely it is used: https://www.nature.com/collections/ksgfknntbs/

There are many pre-existing libraries that already have the implementation to extract radiomic features. So we need to ensure that this can be a part of the pipeline and fine tune based on your approach. 

Looking for people to collaborate on this! Let's do it :)

**Comment by elcronos** [comment]
Everyone please have a look at this:

https://github.com/elcronos/COVID-19/blob/master/CONTRIBUTING.md

We are using Slack now for our communications
