### ISSUE TITLE
Dockerize web app

### ISSUE THREAD

**Issue by franciscohanna92** [elcronos/COVID-19#28]

**Comment by diegoasencio96** [comment]
Que tecnologías tiene la aplicación web ?. Yo podría ayudar a dockerizar la app

**Comment by hectorsanchezmx** [comment]
Es una app de react creada con create-react-app, puedes verla en el repo dentro de /webapp

**Comment by franciscohanna92** [comment]
@diegoasencio96 Feel free to open a PR. The app is located under `/webapp`folder

**Comment by paladium** [comment]
Hello, I would like to complete this task, is it okay if I do the multistage build and run the app with the nginx server?

**Comment by paladium** [comment]
Hey, can you check my pull request #55

**Comment by franciscohanna92** [comment]
this will be followed on https://github.com/FightCOVID19/webapp
