### ISSUE TITLE
Frontend

### ISSUE THREAD

**Issue by sachin-pro** [elcronos/COVID-19#3]
Hi @elcronos this is an amazing initiative, congratulations on starting it. I am a software engineer from Los Angeles, focused on developing Android applications. I'd love to contribute to this cause!

Frontend devs (Android/iOS/Web) feel free to comment on this issue. Let's get this going 💪

**Comment by franciscohanna92** [comment]
I'm in!

**Comment by elcronos** [comment]
Everyone please have a look at this:

https://github.com/elcronos/COVID-19/blob/master/CONTRIBUTING.md

We are using Slack now for our communications
