### ISSUE TITLE
Login Screen UI + Functionality for Android

### ISSUE THREAD

**Issue by sachin-pro** [elcronos/COVID-19#35]

**Comment by GovindaPaliwal** [comment]
Hi I am  Android App Developer from India, focused on developing Native Android applications. 
I'd love to contribute.
feel free to comment / task on this issue if any.

**Comment by ashishkhuraishy** [comment]
Hey I'm a flutter dev. I saw that you are doing the project using native android. If you change your mind and i could help you, i would really love that :)

**Comment by franciscohanna92** [comment]
This will be followed on https://github.com/FightCOVID19/android-app
