### ISSUE TITLE
Image capturing feature for Android

### ISSUE THREAD

**Issue by sachin-pro** [elcronos/COVID-19#36]
#### 2. When finished, it should return to the app and image must be saved somewhere locally (figure out the best way)

NOTE: The intent to start image capturing would be on Home Screen after login called "Upload X-Ray"

### Example:
![Camera](https://user-images.githubusercontent.com/5248843/77244755-2e2b8980-6bd6-11ea-9e50-2bd141766805.png)

**Comment by franciscohanna92** [comment]
This will be followed on https://github.com/FightCOVID19/android-app
