### ISSUE TITLE
Cloud+Api

### ISSUE THREAD

**Issue by Minfante377** [elcronos/COVID-19#5]
Hi, I'm currently working as a software engineer in the AI industry, focused mainly on video analysis. I do not have a huge experience, but I would be glad if I could help with the implementation. Probability it would be good if this app is deployed on a cloud server, where users couls upload images and get the result using an API, or maybe with some basic web app for this porpouse.

**Comment by elcronos** [comment]
Hi @Minfante377. I agree with you. However, I want this server to be agnostic to the cloud platform. At the moment, I'm looking for some support from Microsoft and Amazon to get some free credits from their platforms. One way of making this API usable independently from the Cloud platform is using Docker. Today I will be uploading the first Server API version in docker so the devs can test it in their machines locally. If we get some credits this week I will put it on the cloud.

**Comment by nietzscheson** [comment]
I can help configure the project in AWS Serverless services... soon I send it a PR... Serverless is too easy to deploy!

**Comment by elcronos** [comment]
Great Cristian ! Please feel free to join our slack channel to get in contact with the other devs

**Comment by elcronos** [comment]
@nietzscheson Any progress with this?
