### ISSUE TITLE
Train / val / test contain duplicate images

### ISSUE THREAD

**Issue by edbeeching** [elcronos/COVID-19#51]
It looks like you have not split your data correctly.

**Comment by elcronos** [comment]
@edbeeching We have made an important announcement recently. We will continue working on those images but we have slight change of direction:
https://github.com/elcronos/COVID-19/blob/master/README/new_direction.pdf

**Comment by elcronos** [comment]
Our priority has changed drastically in the last couple of days.  We will be focusing in other areas of our initiative and will only release a dataset once we know it is up to standards expected by the scientific community. Thanks for the comment.
