### ISSUE TITLE
Nothing New Here?

### ISSUE THREAD

**Issue by glenn-jocher** [elcronos/COVID-19#52]
There's a reddit thread that seems to sum up the common consensus that there is no actual work in detection presented by this repo, merely hype and marketing.
https://www.reddit.com/r/MachineLearning/comments/fni5ow/d_why_is_the_ai_hype_absolutely_bonkers/

**Comment by elcronos** [comment]
Hi @glenn-jocher, we have made an important announcement recently: https://github.com/elcronos/COVID-19/blob/master/README/new_direction.pdf

**Comment by Cyril9227** [comment]
Even the ML methodology is fraudulent, he is mixing up train and test images lol

What a sad way to market yourself
