### ISSUE TITLE
DELETING ISSUES

### ISSUE THREAD

**Issue by glenn-jocher** [elcronos/COVID-19#58]
OP is deleting issues to conceal fraudulent nature of repo.

**Comment by elcronos** [comment]
Hi @glenn-jocher that's not the reason. Please do not say things like that without the whole context. This project has evolved very quickly and now is the the result of a collective group of people. The reason we are deleting issues es that contributors are moving everything to: https://github.com/FightCOVID19 as it is easier for manteinance to have different groups. This is not my 'project' anymore. So this repo will be deprecated. We have a change of vision now and I am more than happy to talk to you in person and put you in context of everything. But please stop spreading false rumors or accusations. Could we please have a video call and I promise to explain to you everything. Thanks for your understanding.

**Comment by franciscohanna92** [comment]
Hi @glenn-jocher. I was cleaning some issues that were resolved, and other that should be continued on the Organization Github page as @elcronos stated.
