### ISSUE TITLE
Idea: use computer vision to detect COVID infection from microscope images of saliva and blood

### ISSUE THREAD

**Issue by Tylersuard** [elcronos/COVID-19#61]
Would this work?

**Comment by elcronos** [comment]
@Tylersuard Any papers that support this claim with other viruses?

**Comment by Tylersuard** [comment]
No, but here is a similar project using computer vision to detect bacteria and viruses in water:

https://m.youtube.com/watch?v=TgCKbafpPJM

**Comment by franciscohanna92** [comment]
This is a good idea but for the moment is out of the scope of the project. We will be focusing on x-ray images.
