### ISSUE TITLE
Slack channel invite link is expired

### ISSUE THREAD

**Issue by jeremykohn** [elcronos/COVID-19#64]
Hi, 

I clicked on the [Slack invite](https://join.slack.com/t/covid-19detector/shared_invite/zt-cw28jq9g-2FcPBD~zNRYLnVhr34hrRQ) on the project's [CONTRIBUTING.md page](https://github.com/elcronos/COVID-19/blob/master/CONTRIBUTING.md), but it says "This invite link is no longer active."

Is there still a way to join the Slack channel?

**Comment by franciscohanna92** [comment]
Hi jeremy! Sorry for the late response. Here it is: https://join.slack.com/t/covid-19detector/shared_invite/zt-drgeps78-RK0PjFHKVWwSYMxmLHypZg
